const actionTypes = Object.freeze({
    //app
    APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
    SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',
    CHANGE_LANGUAGE : 'CHANGE_LANGUAGE',

     

    //user
    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
    USER_LOGIN_SUCCESS : 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAIL : 'USER_LOGIN_FAIL',
    PROCESS_LOGOUT : 'PROCESS_LOGOUT',

    //TEST
    START : "XIN CHAO 550 ANH EM",
    SUCCESS : "SUCCESS",
    FAILED : "FAILED",

     //Chức Danh - Position
     POSITION_START: 'POSITION_START',
     POSITION_SUCCESS : 'POSITION_SUCCESS',
     POSITION_FAIL : 'POSITION_FAIL',


     //ROLE- Vai Trò
     ROLE_START: 'ROLE_START',
     ROLE_SUCCESS : 'ROLE_SUCCESS',
     ROLE_FAIL : 'ROLE_FAIL',
     
     CREATE_START : "CREATE_START",
     CREATE_SUCESS : "CREATE_SUCESS",
     CREATE_FAILED : "CREATE_FAILED",

    //GET ALLL USER- Lấy Tất Cả User
    GETALL_START : "GETALL_START",
    GETALL_SUCESS : "GETALL_SUCESS",
    GETALL_FAILED : "GETALL_FAILED",


    //Delete USER- XOÁ
    DELETE_START : "DELETE_START",
    DELETE_SUCCESS : "DELETE_SUCCESS",
    DELETE_FAIL : "DELETE_FAIL",


    //UPDATE USER- Cập Nhật
    UPDATE_START : "UPDATE_START",
    UPDATE_SUCCESS : "UPDATE_SUCCESS",
    UPDATE_FAIL : "UPDATE_FAIL",


    //GETDOCTOR - Lấy Bác Sĩ
    GETDOCTOR_START : "GETDOCTOR_START",
    GETDOCTOR_SUCCESS : "GETDOCTOR_SUCCESS",
    GETDOCTOR_FAIL : "GETDOCTOR_FAIL",


     //GETAllDOCTOR - Lấy Bác Sĩ
     GETALLDOCTOR_START : "GETALLDOCTOR_START",
     GETALLDOCTOR_SUCCESS : "GETALLDOCTOR_SUCCESS",
     GETALLDOCTOR_FAIL : "GETALLDOCTOR_FAIL",
     
    
})

export default actionTypes;